title: joyce's blog
author: joyce song
description: a collection of findings, opinions, and other things i'd like to share on my corner of the internet
email: joyceleste@gmail.com

description: > # description of the site (multiple lines allowed)
  I'm joy-celeste, known as JC to my friends. SF bay area-based software engineer who likes birds, cycling, gudetama, hanfu and design. <br>
  <b>NOTE:<b> All opinions are my own and are not reflective of present, past, or future employers.

favicon: "logo.png" # name+extension of favicon (which must be put on the root folder)
# goat_counter: "yoursitename" # put your GoatCounter name if you want to use GoatCounter analytics

remote_theme: riggraz/no-style-please

theme_config:
  appearance: "auto" # can be "light", "dark" or "auto"
  back_home_text: ".." # customize text for homepage link in post layout
  date_format: "%Y-%m-%d" # customize how date is formatted
  show_description: true # show blog description in home page
