title: urban bird thoughts
author: joy-celeste
description: a collection of findings, opinions, and other things i'd like to share on my corner of the internet
email: donotemail@gmail.com

url: 'https://joy-celeste.github.io/'
baseurl: 'blog'

description: > # description of the site (multiple lines allowed)
  Hi, I'm JC. SF bay area-based software engineer who loves creative work. Always chasing self-actualization.<br><br>
  <b>NOTE:</b> All opinions are my own and are not reflective of present, past, or future employers.

favicon: "logo.png" # name+extension of favicon (which must be put on the root folder)
# goat_counter: "yoursitename" # put your GoatCounter name if you want to use GoatCounter analytics

remote_theme: riggraz/no-style-please

theme_config:
  appearance: "auto" # can be "light", "dark" or "auto"
  back_home_text: "⬅️ back to home" # customize text for homepage link in post layout
  date_format: "%Y-%m-%d" # customize how date is formatted
  show_description: true # show blog description in home page

